"""Mensajes graciosos de Pokémon para la barra de estado mientras se piensa."""

from __future__ import annotations

FUNNY_MESSAGES: list[str] = [
    "Tortilleando Exeggcutes…",
    "Contando Mausholds…",
    "Rascando Pikachus…",
    "Dando massajes a Chansey…",
    "Enseñando a Psyduck a hacer cuadrados…",
    "Persuadiendo a Snorlax de que se aparte…",
    "Puliendo las escamas de Milotic…",
    "Ordenando los cubiertos de Sinistea…",
    "Abrazando a Wooper para que se mueva…",
    "Afilando las cuchillas de Kartana…",
    "Poniendo photocall a Rotom…",
    "Empapando a Squirtle (luego se queja)…",
    "Peinando a Fidough con batidora…",
    "Escondiendo bayas de Munchlax…",
    "Poniendo a Magikarp a nadar a contracorriente…",
    "Convenciendo a Meowth de que comparta…",
    "Tejiendo nudos en Sprigatito…",
    "Sincronizando bostezos de Abra…",
    "Dibujando mostachos a Tepig…",
    "Haciendo la siesta con Hippopotas…",
    "Remangándole el cazador a Gengar…",
    "Cociendo imágenes con Leavanny…",
    "Desenredando a Tangela…",
    "Afinando el canto de Jigglypuff…",
    "Lustrando el casco de Escargrow…",
    "Haciendo apilables a Diglett…",
    "Buceando con Vaporeon por el tintero…",
    "Cargando las placas de Jirachi…",
    "Contando estrellas con Espeon…",
    "Iluminando a Umbreon con la luna…",
    "Horneando pan de Fidough…",
    "Vigilando que Impidimp no meta el dedo…",
    "Poniendo calcetines a Maushold…",
    "Practicando poses con Mr. Mime…",
    "Echando porporina a los Igglybuff…",
    "Midiendo a Eevee con folios A4…",
    "Picoteando semillas con Pidgey…",
    "Secándole la melena a Vaporeon…",
    "Dando vueltas a Exeggcute en la sartén…",
    "Buscando a Ditto entre las imágenes…",
    "Planchando la capa de Mimikyu…",
    "Ajustando la antena de Porygon…",
    "Regando las flores de Bellossom…",
    "Contando monedas de Gimmighoul…",
    "Remendando el sombrero de Hatterene…",
    "Soplando las velas de Litwick…",
    "Encendiendo la cola de Charmander…",
    "Abanicando a Snom para que no se derrita…",
    "Ordenando los discos de Chatot…",
    "Hilando la seda de Tarountula…",
    "Esponjando la nube de Swablu…",
    "Aplaudiendo con Cinccino…",
    "Bordando el chaleco de Quaxly…",
    "Puliendo las gemas de Sableye…",
    "Sirviendo té con Polteageist…",
    "Enrollando a Furret como una croqueta…",
    "Peinando la melena de Pyroar…",
    "Afilando el puerro de Farfetch'd…",
    "Doblando la cinta de Sylveon…",
    "Midiendo la sonrisa de Gengar…",
    "Guardando silencio con Whismur…",
    "Bailando un poco con Oricorio…",
    "Sacando brillo a Klefki…",
    "Contando plumas de Altaria…",
]

FUNNY_MESSAGES_EN: list[str] = [
    "Scrambling Exeggcutes…",
    "Counting Mausholds…",
    "Scratching Pikachus…",
    "Massaging Chansey…",
    "Teaching Psyduck to make squares…",
    "Persuading Snorlax to move over…",
    "Polishing Milotic's scales…",
    "Sorting Sinistea's cutlery…",
    "Hugging Wooper so it moves…",
    "Sharpening Kartana's blades…",
    "Setting up a photo booth for Rotom…",
    "Soaking Squirtle (it will complain later)…",
    "Brushing Fidough with a whisk…",
    "Hiding berries from Munchlax…",
    "Making Magikarp swim upstream…",
    "Convincing Meowth to share…",
    "Tying knots in Sprigatito…",
    "Synchronizing Abra's yawns…",
    "Drawing moustaches on Tepig…",
    "Napping with Hippopotas…",
    "Rolling up Gengar's sleeves…",
    "Stitching images with Leavanny…",
    "Untangling Tangela…",
    "Tuning Jigglypuff's song…",
    "Polishing Escargrow's shell…",
    "Making Diglett stackable…",
    "Diving with Vaporeon through the inkwell…",
    "Charging Jirachi's plates…",
    "Counting stars with Espeon…",
    "Lighting up Umbreon with the moon…",
    "Baking Fidough bread…",
    "Watching that Impidimp doesn't poke it…",
    "Putting socks on Maushold…",
    "Practicing poses with Mr. Mime…",
    "Sprinkling glitter on the Igglybuff…",
    "Measuring Eevee with A4 sheets…",
    "Pecking seeds with Pidgey…",
    "Drying Vaporeon's mane…",
    "Tossing Exeggcute in the pan…",
    "Looking for Ditto among the images…",
    "Ironing Mimikyu's cloak…",
    "Adjusting Porygon's antenna…",
    "Watering Bellossom's flowers…",
    "Counting Gimmighoul's coins…",
    "Mending Hatterene's hat…",
    "Blowing out Litwick's candles…",
    "Lighting Charmander's tail…",
    "Fanning Snom so it doesn't melt…",
    "Sorting Chatot's records…",
    "Spinning Tarountula's silk…",
    "Fluffing Swablu's cloud…",
    "Clapping along with Cinccino…",
    "Embroidering Quaxly's vest…",
    "Polishing Sableye's gems…",
    "Pouring tea with Polteageist…",
    "Rolling up Furret like a croquette…",
    "Brushing Pyroar's mane…",
    "Sharpening Farfetch'd's leek…",
    "Folding Sylveon's ribbons…",
    "Measuring Gengar's grin…",
    "Keeping quiet with Whismur…",
    "Dancing a little with Oricorio…",
    "Shining up Klefki…",
    "Counting Altaria's feathers…",
]


def mensajes() -> list[str]:
    """Lista de mensajes graciosos en el idioma actual."""
    from .i18n import idioma
    return FUNNY_MESSAGES_EN if idioma() == "en" else FUNNY_MESSAGES
